application:
  name: IntegracionLab1
http-client:
  ogit-resource:
    base-url: http://ogit.imp.gob.pe/impapi/
    connect-timeout: 10
    read-timeout: 10
    logging-level: BODY
sheet:
  id: 963862806
spreadsheet:
  id: 12xaeEGPjU16LufeKZCoBh9ArWLHGdNNDo06Gwvumgf0
credentials:
  file:
    path: /credentials.json
tokens:
  directory:
    path: tokens
